data:
    symbol: A,B,C,D
    client: classpath:data/clients.txt
    order: classpath:data/orders.txt
    result: result.txt

logging:
    level:
        ru.smyvin: INFO
    pattern:
        console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"